spring:
  activemq:
    broker-url: tcp://localhost:61616
    
camel:
  component:
    kafka:
      brokers: localhost:9092
      
# Parâmetros para customizar o camel como quiser      
time-period-default: 5000